available

diff --git a/rootfs/container/base/functions/container/build.d/aaa-core b/rootfs/container/base/functions/container/build.d/aaa-core
--- a/rootfs/container/base/functions/container/build.d/aaa-core
+++ b/rootfs/container/base/functions/container/build.d/aaa-core
@@ -158,7 +158,7 @@ sanity_var() {
     output_off
     print_debug "Looking for existence of $1 environment variable"
     if [ ! -v "$1" ]; then
-        print_error "No $2 Entered! - Set '\$$1'"
+        print_error "No '$2' Entered! - Set '\$$1'"
         exit 1
     fi
     output_on
@@ -224,6 +224,330 @@ showoff() {
     echo ""
     echo "H4sIAAAAAAAAAyXK0QmAMAwFwH+nyADFMdyj0BcQUxPTRHF7C34e3KZOI83Uo1DDDVHrOCfSWg2MQvVsxKiRDnJciRHEKbyL/JNzjv7So36syweBXN0TUgAAAA==" | base64 -d | gunzip
     echo ""
+    output_on
+}
+
+truefalse_yesno() {
+    ## Convert TRUE or FALSE statements to either yes or no
+    ## Usage: 'truefalse_yesno varname'
+    ## Don't prefix it with a $
+    ## Optionally add "uppercase" / "lowercase" as second value on how you wish it to be replaced
+    output_off
+    value=$(set | grep "${1}"= | cut -d '=' -f2)
+    var=$(set | grep "${1}"= | sed "s/=.*//g")
+
+    if [ "${value,,}" = "true" ] || [ "${value,,}" = "yes" ] ; then
+        print_debug "Converting Variable Name ${var} value to 'yes'"
+        unset "$1"
+        if [ -n "$2" ] ; then
+            case "${2,,}" in
+                "uppercase" | "upper" | "uc" )
+                    export "$1=YES"
+                ;;
+                "lowercase" | "lower" | "lc" )
+                    export "$1=yes"
+                ;;
+            esac
+        else
+            export "$1=yes"
+        fi
+        elif [ "${value,,}" = "false" ] || [ "${value,,}" = "no" ] ; then
+        print_debug "Converting Variable Name ${var} value to 'no'"
+        unset "$1"
+        if [ -n "$2" ] ; then
+            case "${2,,}" in
+                "uppercase" | "upper" | "uc" )
+                    export "$1=NO"
+                ;;
+                "lowercase" | "lower" | "lc" )
+                    export "$1=no"
+                ;;
+            esac
+        else
+            export "$1=no"
+        fi
+    fi
+    output_on
+}
+
+
+transform_var() {
+    output_off
+    case "${1,,}" in
+        "file" )
+            ## Docker Secrets Support with recursive search in /run/secrets
+            ## usage: transform_var file VAR
+            ##    ie: transform_var file 'XYZ_DB_PASSWORD'
+            ##        (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
+            local variables
+            variables=$(echo "$@" | tr " " "\n")
+            for variable in $variables; do
+                if [ -v "${variable}"_FILE ]; then
+                    # If <VAR>_FILE exists, use it
+                    file_variable=${variable}_FILE
+                    if [ ! -f "${!file_variable}" ]; then
+                        print_error "[transform_var (file)] ${variable}_FILE set as environment variable, however file doesn't exist"
+                        return 1
+                    fi
+                    export "${variable}"="$(cat "${!file_variable}")"
+                else
+                    # If <VAR>_FILE does not exist, search in /run/secrets recursively
+                    _secret_file=$(find /run/secrets -type f -name "${variable}" 2>/dev/null | head -n 1)
+                    if [ -n "${_secret_file}" ]; then
+                        print_debug "[transform_var (file)] Found secret file for ${variable} in /run/secrets: ${_secret_file}"
+                        export "${variable}"="$(cat "${_secret_file}")"
+                    fi
+                fi
+            done
+            unset file_variable
+            unset variables
+        ;;
+        "populate" )
+            ### Populate variable with default or otherwise
+            ### Usage transform_var populate VAR1 VAR2 <mandatory>
+            ### Look to see if VAR1 has a value of unset, if true then skip actions
+            ### Look to see if there is a DEFAULT_VAR2 value. If so, make value of VAR2 DEFAULT_VAR2
+            ### If 'mandatory' is placed as an option, if the VAR2 or DEFAULT_VAR2 doesn't exist, fail spectacularly
+            local defvariable
+            local defvalue
+            local variable
+            local value
+            if set -o posix ; set | grep -q "^DEFAULT_${3}" ; then
+                defvariable=$(set -o posix ; set | grep "^DEFAULT_${3}")
+                defvalue=$(echo "${defvariable}" | cut -d= -f2)
+                defvariable=$(echo "${defvariable}" | cut -d= -f1)
+            fi
+
+            if set -o posix ; set | grep -q "^${2}" ; then
+                variable=$(set -o posix ; set | grep "^${2}")
+                value=$(echo "${variable}" | cut -d= -f2)
+                variable=$(echo "${variable}" | cut -d= -f1)
+
+                if [ "${value}" = "unset" ] ; then
+                    unset "${3}"
+                else
+                    export "${3}"="${value}"
+                fi
+
+            elif [ -n "${defvalue}" ]; then
+                export "${3}"="${defvalue}"
+            else
+                if [ "${4}" = "mandatory" ]; then
+                    print_error "[transform_var (populate)] Need existence of var '${2}' and no DEFAULT_ exists"
+                    exit 1
+                fi
+            fi
+        ;;
+        tonum_* )
+            ## Convert variables to a numbered variable
+            ## usage: transform_var tonum_01 VAR
+            ##    ie: transform_var tonum 01 'XYZ_DB_PASSWORD'
+            ##        (will output $XYZ01_DB_PASSWORD)
+
+            local variables
+            variables=$(echo "$@" | tr " " "\n")
+            for variable in $variables; do
+                if [ -v "${variable}" ] ; then
+                    export "$(echo $(echo "${variable}" | cut -d _ -f 1)${1/tonum_/}_$(echo "${variable}" | cut -d_ -f 2-))=${!variable}"
+                    unset "${variable}"
+                fi
+            done
+            unset variables
+        ;;
+    esac
+    output_on
+}
+
+truefalse_onoff() {
+    ## Convert TRUE or FALSE statements to either yes or no
+    ## Usage: 'truefalse_yesno varname'
+    ## Don't prefix it with a $
+    ## Optionally add "uppercase" / "lowercase" as second value on how you wish it to be replaced
+    output_off
+    value=$(set | grep "${1}"= | cut -d '=' -f2)
+    var=$(set | grep "${1}"= | sed "s/=.*//g")
+
+    if [ "${value,,}" = "true" ] || [ "${value,,}" = "yes" ] ; then
+        print_debug "Converting Variable Name ${var} value to 'On'"
+        unset "$1"
+        if [ -n "$2" ] ; then
+            case "${2,,}" in
+                "uppercase" | "upper" | "uc" )
+                    export "$1=ON"
+                ;;
+                "lowercase" | "lower" | "lc" )
+                    export "$1=on"
+                ;;
+            esac
+        else
+            export "$1=ON"
+        fi
+        elif [ "${value,,}" = "false" ] || [ "${value,,}" = "no" ] ; then
+        print_debug "Converting Variable Name ${var} value to 'Off'"
+        unset "$1"
+        if [ -n "$2" ] ; then
+            case "${2,,}" in
+                "uppercase" | "upper" | "uc" )
+                    export "$1=OFF"
+                ;;
+                "lowercase" | "lower" | "lc" )
+                    export "$1=off"
+                ;;
+            esac
+        else
+            export "$1=off"
+        fi
+    fi
+    output_on
+}
+
+truefalse_onezero() {
+    ## Convert TRUE or FALSE statements to either 1 or 0
+    ## Usage: 'truefalse_onezero varname'
+    ## Don't prefix it with a $
+    output_off
+    value=$(set | grep "${1}"= | cut -d '=' -f2)
+    var=$(set | grep "${1}"= | sed "s/=.*//g")
+
+    if [ "${value,,}" = "true" ] || [ "${value,,}" = "yes" ] ; then
+        print_debug "Converting Variable Name ${var} value to '1'"
+        unset "$1"
+        export "$1=1"
+        elif [ "${value,,}" = "false" ] || [ "${value,,}" = "no" ] ; then
+        print_debug "Converting Variable Name ${var} value to '0'"
+        unset "$1"
+        export "$1=0"
+    fi
+    output_on
+}
+
+var_false() {
+    ## Timesaver for if statements
+    ## Usage: if var_false $VARNAME ; then ... fi
+    [ "${1,,}" = "false" ] || [ "${1,,}" = "no" ]
+}
+
+var_notfalse() {
+    [ "${1,,}" != "false" ]
+}
+
+var_nottrue() {
+    [ "${1,,}" != "true" ]
+}
+
+var_true() {
+    [ "${1,,}" = "true" ] || [ "${1,,}" = "yes" ]
+}
+
+var_value() {
+    if [ "${2}" ] ; then
+        echo "$(grep -oE "^${1}=.*" "${2}" | grep -oP "(?<==).*")"
+    else
+        echo "$(set -o posix ; set | grep -oE "^${1}=.*" | grep -oP "(?<==).*")"
+    fi
+}
+
+wait_for_directory() {
+    ## Wait for Directory to exist
+    ## Usage: wait_for_directory socketname
+    output_off
+    print_debug "Looking for existence of directory: $1"
+    while [ ! -d "${1}" ] ; do
+        sleep 1
+    done
+    output_on
+}
+
+wait_for_file() {
+    ## Wait for File to exist
+    ## Usage: wait_for_file filename
+    output_off
+    print_debug "Looking for existence of file: $1"
+    while [ ! -f "${1}" ] ; do
+        sleep 1
+    done
+    output_on
+}
+
+wait_for_process() {
+    ## Wait for Process to start
+    ## Usage: wait_for_process hostname port
+    output_off
+    print_debug "Looking for existence of process: $1"
+    counter=0
+    while ! pgrep "${1}" > /dev/null ; do
+        sleep 5
+        (( counter+=5 ))
+        print_warn "Waiting for '${1}' to start, retrying.. ($counter seconds so far)"
+    done
+    output_on
+}
+
+wait_for_port() {
+    ## Wait for Port to exist
+    ## Usage: wait_for_port hostname port
+    output_off
+    print_debug "Looking for existence of listening port on $1:$2"
+    counter=0
+    while ! (nc -z "${1}" "${2}") ; do
+        sleep 5
+        (( counter+=5 ))
+        print_warn "Host '${1}' is not listening on port '${2}', retrying.. ($counter seconds so far)"
+    done
+    output_on
+}
+
+wait_for_socket() {
+    ## Wait for Socket to exist
+    ## Usage: wait_for_socket socketname
+    output_off
+    print_debug "Looking for existence of socket: $1"
+    while [ ! -S "${1}" ] ; do
+        sleep 1
+    done
+    output_on
+}
+
+yesno_truefalse() {
+    ## Convert YES or NO statements to either TRUE or FALSE
+    ## Usage: 'yesno_truefalse varname'
+    ## Don't prefix it with a $
+    ## Optionally add "uppercase" / "lowercase" as second value on how you wish it to be replaced
+    output_off
+    value=$(set | grep "${1}"= | cut -d '=' -f2)
+    var=$(set | grep "${1}"= | sed "s/=.*//g")
+
+    if [ "${value,,}" = "true" ] || [ "${value,,}" = "yes" ] ; then
+        print_debug "Converting Variable Name ${var} value to 'yes'"
+        unset "$1"
+        if [ -n "$2" ] ; then
+            case "${2,,}" in
+                "uppercase" | "upper" | "uc" )
+                    export "$1=TRUE"
+                ;;
+                "lowercase" | "lower" | "lc" )
+                    export "$1=true"
+                ;;
+            esac
+        else
+            export "$1=TRUE"
+        fi
+        elif [ "${value,,}" = "false" ] || [ "${value,,}" = "no" ] ; then
+        print_debug "Converting Variable Name ${var} value to 'no'"
+        unset "$1"
+        if [ -n "$2" ] ; then
+            case "$2" in
+                "uppercase" | "upper" | "uc" )
+                    export "$1=FALSE"
+                ;;
+                "lowercase" | "lower" | "lc" )
+                    export "$1=false"
+                ;;
+            esac
+        else
+            export "$1=FALSE"
+        fi
+    fi
     output_on
 }
 
