fix build.log noise

diff --git a/rootfs/container/base/functions/container/available/repository b/rootfs/container/base/functions/container/available/repository
--- a/rootfs/container/base/functions/container/available/repository
+++ b/rootfs/container/base/functions/container/available/repository
@@ -57,10 +57,16 @@ clone_git_repo() {
                 _git_heads=$(awk '{ if ($2 ~ /^refs\/heads\//) { sub("refs/heads/", "", $2); print $2 } }' "/tmp/git_refs_${repo_name}" | tr '\n' ' ')
                 _git_tags=$(awk '{ if ($2 ~ /^refs\/tags\//) { sub("refs/tags/", "", $2); print $2 } }' "/tmp/git_refs_${repo_name}" | tr '\n' ' ')
                 export GIT_REPO_REFS_${repo_name^^}="/tmp/git_refs_${repo_name}"
-                echo "[clone_git_repo] Remote heads: ${_git_heads}"
-                echo "[clone_git_repo] Remote tags: ${_git_tags}"
+                if tty -s ; then
+                    _tty=$(tty)
+                    echo "[clone_git_repo] Remote heads: ${_git_heads}" > "${_tty}" 2>/dev/null || true
+                    echo "[clone_git_repo] Remote tags: ${_git_tags}" > "${_tty}" 2>/dev/null || true
+                else
+                    echo "[clone_git_repo] Remote heads: ${_git_heads}" >&2
+                    echo "[clone_git_repo] Remote tags: ${_git_tags}" >&2
+                fi
             else
-                #echo "[clone_git_repo] Warning: unable to query remote refs for ${1}"
+                echo "[clone_git_repo] Warning: unable to query remote refs for ${1}"
             fi
 
             clone_no_single=""
@@ -104,11 +110,11 @@ clone_git_repo() {
                 if [[ "${2}" =~ ^[0-9a-fA-F]{40}$ ]] ; then
                     branchname="cloned_${repo_name}_${2:0:7}"
                     git switch -c "${branchname}" "${2}" 2>/dev/null || git checkout -b "${branchname}" "${2}" 2>/dev/null
-                    echo "[clone_git_repo] Created branch ${branchname} for commit ${2}"
+                    #echo "[clone_git_repo] Created branch ${branchname} for commit ${2}"
                 elif [ -f "/tmp/git_refs_${repo_name}" ] && grep -q -E "refs/tags/${2}$" "/tmp/git_refs_${repo_name}" ; then
                     branchname="tag_${repo_name}_${2}"
                     git switch -c "${branchname}" "refs/tags/${2}" 2>/dev/null || git checkout -b "${branchname}" "refs/tags/${2}" 2>/dev/null
-                    echo "[clone_git_repo] Created branch ${branchname} for tag ${2}"
+                    #echo "[clone_git_repo] Created branch ${branchname} for tag ${2}"
                 fi
             fi
         fi
